package com.spider.amazon.dto;

import lombok.*;

/**
 * @ClassName RequestHeader
 * @Description 公共请求头
 */
@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class RequestHeader {

    /**
     * UUID generated by the caller. 36 characters. Lowercase. Contains hyphens.
     * required
     */
    private String requestId;

    /**
     * Services as session identifier if needed.
     * no required
     */
    private String conversationId;

}
